### ISSUE TITLE
Project Compile error  C1047

### ISSUE THREAD

**Issue by SundayRX** [med0x2e/ExecuteAssembly#2]
Executeassembly-main \ExecuteAssembly\x86-x64(PEB)\Lib\ libz32.lib "was created using a different compiler version from other objects, such as" Release\ gzutil.obj ";Use the same compiler to regenerate all objects and library ExecuteAssembly C:\Users\SundayRXWork\ ExecuteAssembly\x86-x64(PEB)\ExecuteAssembly\LINK 1

**Comment by jfmaes** [comment]
go to project properties and choose VS 2017 to solve this

**Comment by med0x2e** [comment]
Thanks @jfmaes, will close this for now.

**Comment by 0xElessar** [comment]
Sorry for basic question, but do we have install Visual Studio 2017 to build x86 version? In 2019 VS, there is no option to choose VS 2017, re-targeting shows only installed 2019 components :(

**Comment by med0x2e** [comment]
I haven't tried to build it using VS2019, i mainly used VS2017 + Windows SDK 10.0.17134.0 for building/testing.
